sudo: required
language: generic
script: make

compiler:
    - gcc

install:
    - sudo add-apt-repository -y ppa:george-edison55/precise-backports
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update -qq
    - sudo apt-get install -qq cmake-data cmake
    - sudo apt-get install -qq gcc-6 g++-6
    - export CXX="g++-6" CC="gcc-6"

script:
    - cmake .
    - make
