language: generic
script: make


install:
	#
	- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
	- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  	- |
		if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
			CMAKE_URL="http://www.cmake.org/files/v3.7/cmake-3.7.0-Linux-x86_64.tar.gz"
			mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
			export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  	  	fi
  	# Go to the Root directory  
	- cd ..

script:
    - cmake .
    - make
